Add 'https://www.patterns.dev/' to the resources page (https://github…
FrontEnd-ro/frontend.ro pull request #496
Opened 2022-01-01 21:15 UTC by lazarnarcis

….com/FrontEnd-ro/frontend.ro/issues/486)

2022-01-06 17:50 UTC, iampava requested changes
Overall looks good. A few changes only

2022-01-06 17:50 UTC, iampava commented on client/components/learn/Resources/resources-model.ts
> +      title: 'Patterns Dev',
Please move in the books section. Put it in second place, after "You Don't Know JS"

2022-01-06 17:50 UTC, iampava commented on client/components/learn/Resources/resources-model.ts
> +      cover: `${process.env.CLOUDFRONT_PUBLIC}/public/images/resources/patterns.dev.png`,
Please resize the asset to `500px` width. Then rename to `patters-dev_500w.png` (notice the `_500w` at the end, it's the same as all other assets).

2022-01-07 17:41 UTC, lazarnarcis reviewed
i think everything is ok now

2022-01-09 22:17 UTC, iampava requested changes
Almost there

2022-01-09 22:17 UTC, iampava commented on client/components/learn/Resources/resources-model.ts
> +      cover: `${process.env.CLOUDFRONT_PUBLIC}/public/images/resources/patterns.dev.png`,
Here you have `patterns.dev.png` but the actual file name should be `patterns-dev_500w.png` (please rename the png file. You have a typo. Should be **patterns-dev_500w.png**.)

2022-01-11 18:51 UTC, lazarnarcis reviewed
now is ok :)

2022-01-15 08:53 UTC, iampava approved these changes
Great!

2022-01-15 08:53 UTC, merged