Add Sergiu Szatmari to README contributors list
FrontEnd-ro/frontend.ro pull request #637
Opened 2022-03-07 22:01 UTC by sergiu-szatmari

Follow-up to #629

2022-03-11 08:15 UTC, iampava requested changes

2022-03-11 08:15 UTC, iampava commented on README.md
> +            <a href="https://sergiu-szatmari.github.io/"><img src="https://raw.githubusercontent.com/FrontEnd-ro/frontend.ro/master/client/public/images/contributors/sergiu-sz.png" width="120px;" alt
A couple of small things:

1. As mentioned in [CONTRIBUTING.md](https://github.com/FrontEnd-ro/frontend.ro/blob/master/CONTRIBUTING.md#commit-messages) - every commit must have an issue associated. So please create an issue in the repo regarding this task
2. Please rename the photo according to your full github username. This is the pattern we're using
3. Squash all commits into one. I will merge after that :D

2022-03-15 08:55 UTC, iampava requested changes
I think you didn't correctly fetch the changes from master.

It looks like you have 20 files chaged...
<img width="239" alt="image" src="https://user-images.githubusercontent.com/11327761/158341490-f775d7ed-977f-483c-b2f5-ec39219c1f3b.png">

2022-03-15 18:55 UTC, sergiu-szatmari commented
@iampava i did fetch the upstream changes but because of the squash Github everything that the squash commit contained as a change from me :laughing: . Should be good now. Can't you also merge as squash commit frum GitHub console? Just like in BitBucket? :thinking:

2022-03-18 07:33 UTC, iampava commented
Hey @sergiu-szatmari! There are still 2 commits here 😬

Regarding me squashing and merging, I think it might be possible but honestly never done it :D

2022-03-20 14:50 UTC, sergiu-szatmari commented
@iampava this time should be good for real :grin: however, i'd like to suggest the approach in the picture for future mergings, this might be a way of making sure that the squashing was done correctly.

![Screenshot from 2022-03-20 16-49-36](https://user-images.githubusercontent.com/37306151/159168216-2eac5346-6098-42aa-be1c-6f5c9450c68c.png)

Picture taken from [this](https://www.git-tower.com/learn/git/faq/git-squash) article

2022-03-20 19:47 UTC, iampava approved these changes

2022-03-20 19:47 UTC, merged